# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liberal Commitment
email: joep.vanlit@ru.nl
description: A research project into citizens' commitment to liberal democracy across Europe
baseurl: "/liberalcommitment" # the subpath of your site, e.g. /blog
url: "https://jmvanlit.github.io/" # the base hostname & protocol for your site

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/jmvanlit
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: andrewbanchich
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
